version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - 81:80
    environment:
      - MYSQL_ROOT_PASSWORD=$SECRET
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - mysql
  
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - ./data/mysql:/var/lib/mysql
    
