version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_NAME=blog
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=my-secret-pw
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    